### ISSUE TITLE
Numpy package is missing in requirement 

### ISSUE THREAD

**Issue by Thiefaine-dev** [Dessia-tech/dessia_bot_template#26]
In modules test_example.py, numpy is imported but not in required packages. I don't know if it's normal

**Comment by pgibertini** [comment]
Indeed, but it is a requirement of dessia_common and volmdlr.
But more importantly: it is just a showcase. Maybe the right approach to improve this point is to create a showcase that not require numpy.

**Comment by sbendjebla** [comment]
Fixed with #30
